# Generated by Django 3.2.7 on 2021-11-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
